### ISSUE TITLE
pyfsd.utils.import_users无-f命令

### ISSUE THREAD

**Issue by HaoxuanYu2007** [gamecss/pyfsd#7]
![image](https://github.com/cfcsim/pyfsd/assets/137419260/574c88fe-7b3c-4066-982a-f347a709a209)

**Comment by ghost** [comment]
忘记改文档了，现在是  
`python -m pyfsd.utils.import_users cert.txt fsd`
。但是！你先别用，这玩意(pyfsd)正在重写

**Comment by ghost** [comment]
已在 8abe023 中更新文档
